export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";
export const EMPTY_TO_CART="EMPTY_TO_CART";
export const PRODUCT_LIST="PRODUCT_LIST";
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST";